spin_manifest_version = 2

[application]
name = "fermyon-dev"
version = "0.1.0"
description = "The Fermyon Platform website."
authors = ["Fermyon Engineering <engineering@fermyon.com>"]

[application.trigger.http]
base = "/"

[[trigger.http]]
id = "trigger-bartholomew"
component = "bartholomew"
route = "/..."

[[trigger.http]]
id = "trigger-fileserver"
component = "fileserver"
route = "/static/..."

[component.bartholomew]
source = "modules/bartholomew.wasm"
files = ["content/**/*", "templates/*", "scripts/*", "config/*"]

[component.fileserver]
source = "modules/spin_static_fs.wasm"
files = [{ source = "static/", destination = "/" }]
